server:
  port : 8082

spring:
  application:
    name: client

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry=false: true
